hydra:
  output_subdir: null
  run:  
    dir: .

# prompt for video content analysis
model_id: google/gemma-3-27b-it
model_short_name: gemma27b
dataset: FVC
task: inpredict
batch_size: 1
num_frames: 4  # 27B较大，建议减少帧数节省显存
sample_strategy: uniform
para: 
  temperature: 0.000001
  use_api: false  # 本地调用
  load_in_4bit: true  # 强烈建议开启

top_k: 8
reference_name: coverage_0.5_reference_40
