hydra:
  output_subdir: null
  run:  
    dir: .
model_id: Qwen/Qwen3-VL-32B-Instruct
model_short_name: qwen
dataset: FakeSV
task: inpredict
data_split: train
batch_size: 1
num_frames: 8
sample_strategy: uniform
para: 
  temperature: 0.000001
  use_api: true
top_k: 8
reference_name: coverage_0.5_reference_40
