hydra:
  output_subdir: null
  run:  
    dir: .

prompt: 
model_id: Qwen/Qwen3-VL-32B-Instruct
model_short_name: qwen
dataset: FakeSV
task: insight
data_split: train  # 'train' or 'test'
# image_path: [data/FakeSV/frames_16/vid1/00000.jpg, data/FakeSV/frames_16/vid2/00000.jpg]
num_frames: 8  # 视频帧数，默认8帧
sample_strategy: uniform  # uniform: 间隔2帧采样 (0,2,4,6...), sequential: 顺序采样
para: 
  use_api: true  # 设置为true则调用API，false或不设置则使用本地模型
batch_size: 1
threshold: 0.9
pairs_name: pairs_coverage_0.5
insight_name: coverage_0.5